project:
  type: website

website:
  title: "Proyecto Intermodular"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "🏠 Inicio"

      - section: "📚 Unidades"
        contents:
          - text: "1-Gestión de proyectos y metodologías ágiles"
            href: unidades/ud1/index.qmd

      - section: "🧪 Laboratorios"
        contents: 
          - href: laboratorios/ud1/lab1.qmd
            text: "UD1 · Lab 1 · Del reto al briefing y la viabilidad"
          - href: laboratorios/ud1/lab2.qmd
            text: "UD1 · Lab 2 · Del problema al backlog"
    
      - section: "🚀 Desafíos"
        contents:
          - href: desafios/desafio-01/index.qmd
            text: "D1 · LifeOS"


      - href: proyecto-final/index.qmd
        text: "🏆 Proyecto Intermodular Final"


      - href: ia/index.qmd
        text: "🤖 IA"

      - href: recursos/index.qmd
        text: "📦 Recursos"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


